language: php
php:
    - 5.6
    #- 7.0
    #- hhvm
    #- hhvm-nightly

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm-nightly

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - PHALCON_VERSION="2.0.7"

before_script:
    # Update Composer
    - travis_retry composer self-update

    # Install Phalcon
    - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b phalcon-v${PHALCON_VERSION}
    - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j4 > /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
    - php -r 'echo \Phalcon\Version::get()."\n";'

    # Install Nette Tester
    - travis_retry composer install --no-interaction --prefer-source

    # Coveralls
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini >> ./tests/php-unix.ini; fi
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then NTESTER_FLAGS="--coverage ./coverage.xml --coverage-src ./src"; else TESTER_FLAGS=""; fi
script:
    # Print phpmodule
    - php -m
    # Print info
    - vendor/bin/tester tests/cases -i -c tests/php-unix.ini
    # Run tests
    - vendor/bin/tester tests/cases -s -c tests/php-unix.ini $NTESTER_FLAGS

after_script:
    # Coveralls
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require satooshi/php-coveralls; fi
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php vendor/bin/coveralls -c tests/.coveralls.yml -v; fi

after_failure:
    # Print *.actual content
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
